### ISSUE TITLE
Misaligned Icons in VisualEditor

### ISSUE THREAD

**Issue by chrom11** [Hutchy68/pivot#87]
### Setup

- Browsers and versions: Chrome 75
- MediaWiki version: 1.32.3
- Database version: MySQL 5.7.26
- PHP version: PHP 7.2.19
- Pivot version: 2.1.0
- Extension version (if connected to the issue): VisualEditor REL1_32 and Parsoid 0.9.0

### Issue

The icons are misaligned when using VisualEditor on the latest version of Pivot. Strangely the issue is inconsistent, it affects certain icons but leaves others alone.

![misaligned](https://user-images.githubusercontent.com/52811963/62193021-b3062200-b32b-11e9-87a0-e92d8021848f.png)

**Comment by kghbln** [comment]
That's the hot fix for your wiki: [CSS diff](https://pivot.wikiproject.net/w/index.php?title=MediaWiki:Pivot.css&diff=315&oldid=127)

**Comment by s0rin** [comment]
That's great, the hot fix works, but the icons from the dropmenu to toggle from visual to source editing are still misaligned.
 
![mw_visual_editor_dropdown](https://user-images.githubusercontent.com/9009220/63356029-68def200-c367-11e9-8004-75d08533fad5.png)

**Comment by kghbln** [comment]
Well, the fix in one location creates the issue in another one. You can use this for better results but be aware that this is still not ideal. However, I do not have more time for this now, meaning you are welcome to fiddle with CSS to get this back on track for a 100%.

```css
/* Fix edit bar of VisualEditor at least for MediaWiki 1.31 and later */
.oo-ui-tool .oo-ui-tool-link {
    padding-top: 0;
}
.oo-ui-popupToolGroup .oo-ui-tool-link .oo-ui-tool-accel,
.oo-ui-popupToolGroup .oo-ui-tool-link .oo-ui-tool-title {
    padding-top: 1em;
}
```
